version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: gadalka-postgres
    environment:
      POSTGRES_DB: gadalka
      POSTGRES_USER: gadalka
      POSTGRES_PASSWORD: gadalka
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: