spring:
  application:
    name: gadalka-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/gadalka
    username: gadalka
    password: gadalka
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

telegram:
  auth:
    enable: false
  bot:
    token: "TOKEN_HERE"

jwt:
  secret: ee9ff174288351f5bbb94e6915ff42792fe34dcc7e71e951c4329496b167f586

openrouter:
  api-key: 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
  url: https://openrouter.ai/api/v1/chat/completions
  model: openai/gpt-4o-mini